spring.application.name=payments-api

api.url=https://api.lothuspay.com
internal.secret=${INTERNAL_SECRET}

logging.level.org.springframework.web=DEBUG
logging.file.name=logs/wallet-api.log

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}

spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

misticpay.ci=credential-ci
misticpay.cs=credential-cs

misticpay.ci.black1=credential-ci-black1
misticpay.cs.black1=credential-cs-black1

misticpay.ci.black2=credential-ci-black2
misticpay.cs.black2=credential-cs-black2